steps:
  # Build the container image for linux/amd64
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/talent-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/talent-api:latest'
      - '-f'
      - 'vertex_ai/Dockerfile.demo'
      - '.'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/talent-api:$COMMIT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/talent-api:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talent-analytics-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/talent-api:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/talent-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/talent-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'