services:
  # ML API Service
  ml-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: thai-talent-ml-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Python unbuffered output for real-time logs
      PYTHONUNBUFFERED: 1
      # Google Cloud credentials for GenAI and GCS access
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account.json
    volumes:
      # Mount code for development (hot-reload)
      - ./api:/app/api
      - ./predictive_retention:/app/predictive_retention
      - ./skill_promotion_management:/app/skill_promotion_management
      - ./mock_data:/app/mock_data
      - ./config:/app/config
      # Mount output directory for ML pipeline results
      - ./output:/app/output
      - ./data:/app/data
      # Mount Google service account credential file
      # Replace 'service-account.json' with your actual credential file name
      - ./service-account.json:/app/service-account.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3