services:
  # ML API Service
  ml-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: thai-talent-ml-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Python unbuffered output for real-time logs
      PYTHONUNBUFFERED: 1
    volumes:
      # Mount code for development (hot-reload)
      - ./api:/app/api
      - ./predictive_retention:/app/predictive_retention
      - ./mock_data:/app/mock_data
      - ./config:/app/config
      # Mount output directory for ML pipeline results
      - ./output:/app/output
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3