version: '3.8'

services:
  # PostgreSQL Database for local development
  postgres:
    image: postgres:15
    container_name: thai-talent-wow-local-db
    environment:
      POSTGRES_DB: thai_talent_wow_production
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: TalentWow2024!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d thai_talent_wow_production"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: