FEARURES_MEANING_MAPPER = {
    'age': 'Age of Employee',
    'education_level': 'Education Level of Employee',
    'num_parent': 'Number of Parents',
    'num_children': 'Number of Children',
    'num_siblings': 'Number of Siblings',
    'num_spouse': 'Number of Spouses',
    'job_level': 'Job Level of Employee',
    'department_name': 'Department of Employee',
    'department_name_shap': 'Department of Employee',
    'total_working_year': 'Total Working Years',
    'total_working_year_z_manager': "Total Working Years vs Manager’s Team Average",
    "total_working_year_z_position": "Total Working Years vs Position's Average",
    "total_working_year_z_job_level": "Total Working Years vs Job Level's Average",
    "total_working_year_z_department": "Total Working Years vs Department's Average",
    "num_employee_under_manager": "Number of Employees in Same Department",
    "year_with_current_manager": "Years with Current Manager",
    "num_past_manager": "Number of Past Managers",
    "num_employee_under_position": "Number of Employees in Same Position",
    "num_employee_under_job_level": "Number of Employees in Same Job Level",
    "num_employee_under_department": "Number of Employees in Same Department",
    "salary_z_manager": "Salary vs Manager’s Team Average",
    "salary_z_position": "Salary vs Position Average",
    "salary_z_job_level": "Salary vs Job Level Average",
    "percentage_salary_increase_since_hire": "% Salary Increase Since Hire",
    "year_since_last_salary_adjustment": "Years Since Last Salary Adjustment",
    "salary_compare_market_rate": "Salary Compared to Market Rate",
    "year_in_current_position": "Years in Current Position",
    "num_past_promotions": "Number of Past Promotions",
    "time_since_last_promotion": "Years Since Last Promotion",
    "avg_time_to_promotion": "Average Time to Promotion (Years)",
    "num_training": "Number of Trainings Attended",
    "num_activity": "Number of Activities Participated",
    "num_skills": "Number of Skills Acquired",
    "avg_skills_score": "Employee Average Skills Score",
    "num_skill_gaps": "Number of Skill Gaps Identified",
    "skill_score_vs_avg_position_score": "Skill Score Compared to Average Position Score",
    "skill_score_vs_median_position_score": "Skill Score Compared to Median Position Score",
    "avg_performance_score": "Average Performance Score",
    "performance_score_z_manager": "Performance Score vs Manager’s Team Average",
    "performance_score_z_position": "Performance Score vs Position Average",
    "performance_score_z_job_level": "Performance Score vs Job Level Average",
    "performance_score_z_department": "Performance Score vs Department Average",
    "total_ot_hours_3_months": "Total Overtime Hours (Last 3 Months)",
    "total_sick_leave_hours_3_months": "Total Sick Leave Hours (Last 3 Months)",
    "total_vacation_leave_hours_3_months": "Total Vacation Leave Hours (Last 3 Months)",
    "distance_from_home_to_office": "Distance from Home to Office (km)",
}


FEATURES_ACTION_MAPPER = {
    "age": "Offer career development plans suited for different age groups, such as leadership tracks for older employees or skill-building for younger staff.",
    "education_level": "Provide learning opportunities or advanced roles matching the employee's educational qualifications to increase engagement.",
    "num_parent": "Offer flexible work arrangements or family support benefits to ease work-life balance pressures.",
    "num_children": "Provide childcare assistance, parental leave flexibility, or family-friendly scheduling.",
    "num_siblings": "Promote work-life balance policies to support extended family responsibilities.",
    "num_spouse": "Ensure benefits and insurance plans support family needs and encourage stability.",
    "job_level": "Ensure fair promotion opportunities, role clarity, and workload balance for the job level.",
    "department_name": "Address department-specific workload, culture, or leadership issues through targeted engagement programs.",
    "department_name_shap": "Address department-specific workload, culture, or leadership issues through targeted engagement programs.",
    "total_working_year": "Recognize long service with awards, career progression options, and new challenges to maintain motivation.",
    "total_working_year_z_manager": "If employee tenure is higher than peers, explore leadership opportunities; if lower, enhance onboarding and integration.",
    "total_working_year_z_position": "Adjust responsibilities or career growth opportunities if tenure in position is unbalanced compared to peers.",
    "total_working_year_z_job_level": "Review progression speed and align promotions fairly across job levels.",
    "total_working_year_z_department": "Ensure retention programs are consistent across departments to avoid dissatisfaction.",
    "num_employee_under_manager": "If team size is large, ensure adequate leadership support; if small, provide cross-team collaboration to avoid isolation.",
    "year_with_current_manager": "Encourage manager-employee relationship building and address possible conflicts through coaching.",
    "num_past_manager": "Stabilize management assignments and reduce frequent leadership changes.",
    "num_employee_under_position": "Review workload fairness and ensure competitive pay for positions with higher headcount.",
    "num_employee_under_job_level": "Benchmark pay and growth for employees at the same job level to prevent inequity.",
    "num_employee_under_department": "Provide department-level engagement initiatives and ensure workload balance.",
    "salary_z_manager": "Adjust pay to be competitive with peers under the same manager.",
    "salary_z_position": "Ensure salary is fair compared to others in the same position.",
    "salary_z_job_level": "Review salary structure to avoid disparities within the same job level.",
    "percentage_salary_increase_since_hire": "Offer salary adjustments for employees with low percentage growth over tenure.",
    "year_since_last_salary_adjustment": "Review and adjust pay if salary changes have been long overdue.",
    "salary_compare_market_rate": "Adjust salaries to match or exceed market benchmarks to prevent attrition.",
    "year_in_current_position": "Provide role rotation or upskilling opportunities for employees stuck in the same position for too long.",
    "num_past_promotions": "Reward high performers with more career growth opportunities; re-engage employees with fewer promotions.",
    "time_since_last_promotion": "If promotions are long overdue, provide growth discussions or skill-building opportunities.",
    "avg_time_to_promotion": "Evaluate promotion policies to ensure timely career progression.",
    "num_training": "Increase access to relevant training programs for skill and career growth.",
    "num_activity": "Encourage participation in company events to strengthen engagement and sense of belonging.",
    "num_skills": "Offer skill development plans and cross-training opportunities.",
    "avg_skills_score": "Provide targeted training to improve skill scores where necessary.",
    "num_skill_gaps": "Implement tailored upskilling programs to close critical skill gaps.",
    "skill_score_vs_avg_position_score": "Provide specialized coaching to raise skills to at least position average.",
    "skill_score_vs_median_position_score": "Offer training resources to match or exceed median skill benchmarks.",
    "avg_performance_score": "Provide constructive feedback and support to improve performance scores.",
    "performance_score_z_manager": "Align expectations and feedback within manager’s team to ensure fairness.",
    "performance_score_z_position": "Address discrepancies in performance compared to others in the same position.",
    "performance_score_z_job_level": "Review and address performance differences at the job level.",
    "performance_score_z_department": "Identify and solve department-specific performance issues.",
    "total_ot_hours_3_months": "Reduce excessive overtime through workload balancing and additional resources.",
    "total_sick_leave_hours_3_months": "Promote health and wellness programs to reduce sickness-related absences.",
    "total_vacation_leave_hours_3_months": "Encourage vacation usage for rest and recovery, or adjust workload if vacation is overused.",
    "distance_from_home_to_office": "Offer remote or hybrid work options to reduce commute burden."
}